name = "Cabricality"
author = "DM-Earth"
version = "0.2-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e43a98bc0675e9002b9e976495e681d4bad100d906c8a738aeae6d8c31b470c1"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
