name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e7579eaa25aa7f94c8d9907e3757444ea7323940a189e961b2172ffa047baaf"

[versions]
minecraft = "1.18.2"
quilt = "0.17.10"
