name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b398349ffc668c128919b0cc1147907127ad192c58ee8307acbb74bc76128ec"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
