name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bafac277e70d368653da3ba1043bfaa2b42bae8ea241503e67b176f7976feba"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
