name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b081f8228538e2f94467122641860936b0d1b2532bb3acf5c2eda60e2f0bbed"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
