name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3be367740d173ee4bc507c4aeb05031f6521cfa2aa177563f999a124571477e0"

[versions]
minecraft = "1.18.2"
quilt = "0.17.10"
