name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde4825dafc6f81f43f3402b91da31e17820757d37e6f0cf42f6d5528f41a93e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
