name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d14143f1bc7eb97301c58072232775f67ce9709e7873190e2e72c1eef387765"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
