name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10efc354d99722356fc3f2135e37dfbea6fe65c22cf196eec5d4a878252ba1fc"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
