name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1f6c5284f8fc57ae38c2fea112278091cd195dcbb3eaf5e27c26fcd5f5953a4"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
