name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6eb7dfa3be5dbf79571eea894b06a3557cafc1d55a20b9261f82743d021c8686"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
