name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d725ad6fb1ed7ab90aceb9d997cfb4ad0932d980c0df802bda5c128eb9fd6c3f"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
