name = "Cabricality"
author = "DM-Earth"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cd97f0955707f0917703b60657743fea98f3866c9e487e4a298c539491d2a33"

[versions]
minecraft = "1.18.2"
quilt = "0.18.2"
