name = "Cabricality"
author = "DM-Earth"
version = "0.1-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa1fdecb988fc354198463126eb746c6468143751ba0c92d3983f4ce7ecee0f7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
