name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86685f6fda6f318983df79fd5c6bd1a3d9fd2749aadad145a8a2b1b5206d4bc3"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.4"
