name = "Cabricality"
author = "DM-Earth"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb40de687d75a5d4a08dffd2a1f82eb52aa31186544bf71c6bf0f920ca858618"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
