name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "140c8857f80225a163d64c698f50746402e7b9a45d56da8227b6a2af5573d767"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
