name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b815459e84a372cb28b06b835b9a014fa67ad1a41ee438d401f6d1618644f8da"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
