name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "780f6479009a7e310e0b3f9ea121b8383db9643678b2fb80c4e0fee15619ed74"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
