name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "384ddc8e3eb59108f2fc2f5e57aed95b95da39398328d96ba2145943aeabb156"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
