name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba22ed0558193ea9cf987a9e1a96f830eaf903ac803da259518e42bfd4081116"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
