name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4cd9203832039763f6bd00e84eb562d4cc92b9f2d3c7f15f087b6a588c0067c"

[versions]
minecraft = "1.18.2"
quilt = "0.17.10"
