name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6a498571887e12dab66027c825a4aa5824b1ca88b0e395cb897eea9917cf839"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
