name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev6-fix1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc6142289e2471324cee6ffc5bf8c7e7a1033ad84d082ac66e2282c2b22cc2b"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
