name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53c05c71ed89473a711f427074518b3283d931f6f13969c00c5ccd02b3cc3bfd"

[versions]
minecraft = "1.18.2"
quilt = "0.17.8"
