name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-dev15-fix1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e0f15ebd19edf629ac4b66e8fc20c340af4eab6ac300e5004fdd504be88fc92"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
