name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed775ec888c85cefbb14f16ba483cf6c7931056caa19fffaa8cd879bde668c46"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
