name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75a2a3f13fc4dc9d01687d06b7a6230ccfca0f9918573a025e5a10b3d7d21852"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
