name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b600a6742c3412103f332368a9dbb9b3458c159fb9d8ba54065ed595a6581957"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
