name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4ce1e98b2c1e8be3986dc565e7e6db838e2dd13f168c46118d0350efa54c4d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.8"
