name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ba354a23d36990c29045fd3fb726bfedd8d5f32cfbb14671fd09164185bf6ab"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
