name = "Cabricality"
author = "DM-Earth"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59dac211cea1c5b2bf4564021e99ba61337285e43526a7f04019ae813923c272"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
