name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc72b58bec9faed0e9b5074a8efb565b67706f15f35ed24b7387c48d4476fb7d"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
