name = "Cabricality"
author = "DM-Earth"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "177a07cb3e8f6d2032c0d5d0029b22f319712f0b95dc29a4e38ea7487a2353f5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
