name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-dev18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3837f7c1dd4bd35c65e43b7c3ad1da2a8a1724aba539b2523e0ec2e585510681"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
