name = "Cabricality"
author = "DM-Earth"
version = "0.1-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15d921949b0b265dcd82f47c3a8a0b12d0fcfc0c802a5c4ef6d06a55f5a42957"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
