name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daa382886a2262fb47d86fd72f140b2a35359310393e5ab054baaeb530bff092"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
