name = "Cabricality"
author = "DM-Earth"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afef5ae2bf366e21f2a10152acb9c9b700f6cb702b6c2f703768e22679cbfe64"

[versions]
minecraft = "1.18.2"
quilt = "0.18.2"
