name = "Cabricality"
author = "DM-Earth"
version = "0.2-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d3e82815c1050bfe28b4c1361385b48c53e95e6a0a5c4cb836065fb64e57a22"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
