name = "Cabricality"
author = "DM-Earth"
version = "0.1-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b0f390bb32fdd61953c04b24011d683f81bf71b36fc4f526107d6e7fc50fbcd"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
