name = "Cabricality"
author = "DM-Earth"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be9751a66f0728e96f4ac54fb281f0512aa27cd9f79218b06d15111f74f5b908"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.4"
