name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adbbac246de29e4589f4f80086805b8dce3dddf2f64bce88e458deb9996ccc5a"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
