name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2a2c4886a3e2e3fbd57e28be6538c875058855e1de6e17fc141739cf2841270"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
