name = "Cabricality"
author = "DM-Earth"
version = "0.2-pre4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c057d972e60f13987359f4b68a578cc702ce0a36422024ec79a74451a4c4ed7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
