name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49477ff07eccdd22ddd0dce3ce765c904110cb5900491330533c155135dcb41f"

[versions]
minecraft = "1.18.2"
quilt = "0.17.8"
