name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3acdba1632b9bc6c6636d630da405822c0fa462bcdd5801b156bb786c6d67bb"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
