name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "557f39ef5e26add7ab6b42ceef9472807eb24a613c7e6f007d2e1cd7b5d5814a"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
