name = "Cabricality"
author = "DM Earth"
version = "1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e1423a3eff24cda4620df96488e5c69de86464a0ce0213dd4a7a301ec20a36"

[versions]
minecraft = "1.20.2"
quilt = "0.21.0-beta.5"
