name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3e4af8fbd0f05a338a55f5369225b3031f36c31811db53244349d76a695853e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
