name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e134839b206fde107fab2bee6b1f20555a8be61c449b876f7b1681056de86d5a"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
