name = "Cabricality"
author = "DM Earth"
version = "0.3.1-patch1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aaa5d3957bc5e771b560cd73f0e6a4d68672bb0dd5f6ea832eb72e7e09f176e"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.4"
