name = "Cabricality"
author = "DM-Earth"
version = "0.2-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51a284c5f61a1efd5f6f715332c6729b383d81708889e7e8e7c6e7c921a15762"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
