name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab16575fdcdf89d5a6b9523a6c25f90890427e6059d1d9680fea421ccaf79fd9"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
