name = "Cabricality"
author = "DM Earth"
version = "1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7b818c4fdf64d8275442673a868656cf072cb4489babd23f38bf6a1ea0580b5"

[versions]
minecraft = "1.20.2"
quilt = "0.21.0-beta.5"
