name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20e2f0bfad320cf539fb480684b9966944b485faaeb881be8ee2323b1ae6db10"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
