name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "491f769aa59f977ded9577687ac94cf6c187b39a281ecfd960f9e8af8901e6e8"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
