name = "Cabricality"
author = "DM-Earth"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c66543d9e3fa5577554e42b33cc9d63dfbe3b3ec2267cd598c89f7604a4e92"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
