name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9697edd3706567566b094a787f0725767d9abd4f328d576924d267e206c1e815"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
