name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4825a1994a90a111d7c2a16935f98646164114e8adfd2758a0e76d5fe405a6"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
