name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5692b1d5b199254097688b5624b062ebf47433beeb6f86c40224cf19a800984"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
