name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4baf7b6253c1bb161d69d6de5098018e0c1c2d0023c5ed25898d2c048dcfb5d7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.8"
