name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84e65d88f71d82a5f0d5e9c9878eb2aa583c84be42f5d8beb810b1494307ac17"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
