name = "Cabricality"
author = "DM-Earth"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e87205a9abb91991174710e559fa29ee3cbb675fc1a89c44c35298b3076736c"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
