name = "Cabricality"
author = "DM-Earth"
version = "0.1-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33efd9491a8f7ccad4214449c6147d226b38416557eab129a99b4c12561e232a"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
