name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6270b0e2ef54c1a66d07c76bdde4ea7e7ca2390c4b9f1717ef44e381bf3f8bbe"

[versions]
minecraft = "1.18.2"
quilt = "0.17.8"
