name = "Cabricality"
author = "DM-Earth"
version = "0.1-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4852977da0ca478e4408ee0881547b93fa947aad4e6a3b78814c21fa652683a2"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
