name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "597d9a566f2b9befb1f40fffe813745386cebd0155ad66f9e33e5e8dfd58d2f8"

[versions]
minecraft = "1.18.2"
quilt = "0.17.10"
