name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "313d0342b81dde0ce83796da83f42c26cc53950e778a08fcd89daaf3f8a801c7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.10"
