name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ec65a76b07cd5b229be85c0ff389f13d53087fa2e97cb37a2b36cc635b8a367"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
