name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-dev17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1b3dde93915347b1f20e8667c2a313ccc5f8a9c34e417462c5716c2b34e2250"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
