name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "002b48c8c2872440c15ed1ee30ca826d216b2930a5ee52be7a8f5a4bcb59c3a0"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
