name = "Cabricality"
author = "DM Earth"
version = "1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "288d1a1bfddc3e13c32274ad4229d4e0fd09c4cffde995f75f3dc238cc1dec85"

[versions]
minecraft = "1.20.2"
quilt = "0.21.0-beta.5"
