name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98846c518a6e62ca17366c977e46c79245ed95d2a94aadc3ef7ad7c350f14d79"

[versions]
minecraft = "1.18.2"
quilt = "0.17.10"
