name = "Cabricality"
author = "DM-Earth"
version = "0.2-pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b59aee7fad266b64f91777efe167eb5d9acd6b57bb5af0e826e4b10ce228847"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
