name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b54393392d050cb79c2f3075fb41dd7ba1116cb523b11376cae319fa9a0365"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
