name = "Cabricality"
author = "DM-Earth"
version = "0.2-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5271159d0fe69f5112dcadbd252125c2336987896757a10e7abf8cfd8d6e95a"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
