name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e6b4954c7328c940fb914d5f2b58f7abb17cb5cf5671bf0de7b251838a18a3e"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.2"
