name = "Cabricality"
author = "DM-Earth"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ccaafde98dcbf47067d189880a3562beb96cea226c121c1c5bc0f8f19ffe2d8"

[versions]
minecraft = "1.18.2"
quilt = "0.18.2"
