name = "Cabricality"
author = "DM-Earth"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94f47780377f2da23ed2e2bc7d98a05e0df3fa187eb0a4f9e376ca9808df1bbc"

[versions]
minecraft = "1.18.2"
quilt = "0.20.0-beta.4"
