name = "Cabricality"
author = "DM-Earth"
version = "0.2-beta5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14adccda0ae3afbabc8a02ef8d3daf7b28dc4f5712dde28731b8a848cd246600"

[versions]
minecraft = "1.18.2"
quilt = "0.17.8"
