name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c510b7b0866c202dc15a4ae9aa5dc4b8e19359f559e2fbe953bb5b718f32dee1"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
