name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev9-patch2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "331ca05ff5ba7c025edc7de8a2a7be8613328ac19ea0def34cb5fa9347c80af2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
