name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dad6c1ef031e039bd071ee56b62e86e5881e44612d11cba4898ab386c09c85cd"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
