name = "Cabricality"
author = "DM-Earth"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fdbea8ee06e74a0be94c57dbfe810f7ec70a232e7c4e76dd632bf2795d2dad6"

[versions]
minecraft = "1.18.2"
quilt = "0.17.11"
