name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27a5e4c330f30e57b94208abe1efe5af48ddf45bf52408f6af04fdf8a5352067"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
