name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0306bd4aa03b4630d3a4fb745672dafdc2adb4224b95d07ba146e049c3e49820"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
