name = "Cabricality"
author = "Yjn024"
version = "0.1.0-dev7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3053ab993ae0123be2b2023ff31a204ce298687531aef59ff4a0310f0258f446"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
