name = "Cabricality"
author = "DM-Earth"
version = "0.1.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88758e83df707437419b0a915969ec3d8049150362be2e1e315bc759be64a822"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
