// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('rei.remove.categories', event => {
	event.yeet('minecraft:plugins/tag')
//	event.yeet('alloy_forgery:forging')
	event.yeet('minecraft:plugins/stripping')
	event.yeet('minecraft:plugins/beacon_base')
	event.yeet('minecraft:plugins/beacon_payment')
	event.yeet('minecraft:plugins/pathing')
	event.yeet('minecraft:plugins/waxing')
	event.yeet('minecraft:plugins/wax_scraping')
	event.yeet('minecraft:plugins/oxidizing')
	event.yeet('minecraft:plugins/oxidation_scraping')
	event.yeet('roughlyenoughitems:plugins/information')
	event.yeet('farmersdelight:decomposition')
	event.yeet('ae2:throwing_in_water')
	event.yeet('ae2:condenser')
	event.yeet('ae2:inscriber')
	event.yeet('create:fan_smoking')
	event.yeet('create:fan_blasting')
	event.yeet('create:automatic_shapeless')
	event.yeet('create:automatic_shaped')
	event.yeet('create:automatic_packing')
	event.yeet('create:automatic_brewing')
	event.yeet('create:block_cutting')
	event.yeet('create:item_application')
	event.yeet('create:mystery_conversation')
})