enable_splash_texts = true
enable_festivals = true
follow_client_language = true
colorful = true # Make splash texts a little colorful

[debug]
disable_debug_info = true # Debug info will not be logged if true

[enum]
random_rate = "Both" # Splash Texts Refresh Rate
# Never  - Never show random splash texts
# Reload - Refresh after reloading resources
# Click  - Refresh when clicking the splash text
# Both   - Refresh splash texts when reloading and clicking
splash_mode = "Custom" # Splash Texts Display Mode
# Disabled - Disable splash texts, only show debug info
# Vanilla  - Only show vanilla splash texts
# Custom   - Only show custom splash texts
# Both     - Show both vanilla and custom splash texts
